PECA1=input().split(' ')
PECA1COD=int(PECA1[0])
PECA1QUANTD=int(PECA1[1])
PECA1VAL=float(PECA1[2])

PECA2=input().split(' ')
PECA2COD=int(PECA2[0])
PECA2QUANTD=int(PECA2[1])
PECA2VAL=float(PECA2[2])

VALORAPAGAR=(PECA1QUANTD*PECA1VAL)+(PECA2QUANTD*PECA2VAL)

print('VALOR A PAGAR: R$ {:.2f}'.format(VALORAPAGAR))
